services:
  api:
    build:
      context: .
      dockerfile: src/ProdutosReactAPI.API/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProdutosReact;User Id=sa;Password=r@f@eL-123!;TrustServerCertificate=true;
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/swagger"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "r@f@eL-123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'r@f@eL-123!' -C -Q 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  sql_data:
